### ISSUE TITLE
Build a stop watch with html, css, javascript.

### ISSUE THREAD

**Issue by pranavbharadwaj007** [Hacktoberfest-SCE/Build-It-Now#7]

**Comment by Harsh97x** [comment]
Hey, @pranavbharadwaj007 I would like to work on this. Please assign me.

**Comment by codegoggins** [comment]
Hey !
This is my very first time contributing to open source. How exactly should I contribute to this project ? I am new to Open Source , it would be great if you could help. It would be great if you would assign me this task.

**Comment by Tusharjain123** [comment]
Hey @pranavbharadwaj007, Can I work on this issue?

**Comment by valak-69** [comment]
Can i also work on this @pranavbharadwaj007
